version: "3.9"

services:
  app:
    build: .
    ports:
      - "8222:8222"
    environment:
      SESSION_SECRET: CHANGE_ME_TO_A_LONG_RANDOM_SECRET
      ADMIN_USER: admin
      ADMIN_PASS: admin123
      GITHUB_REPO: anthonyhales/mealie_recipe_crawler/
    volumes:
      - ./data:/app/data
    restart: unless-stopped
