version: "3.9"

services:
  mealie-recipe-crawler:
    build: .
    container_name: mealie-recipe-crawler
    ports:
      - "8222:8222"
    environment:
      # Change this to a long random string. Example:
      # python -c "import secrets; print(secrets.token_hex(32))"
      - SESSION_SECRET=;DTIIv|k.lA,2vuRjCqugxsPXB~mz}
      - ADMIN_PASS=admin123
        GITHUB_REPO=anthonyhales/mealie_recipe_crawler/
      - ADMIN_USER=admin
    volumes:
      - ./data:/app/data
    restart: unless-stopped
